#!/usr/bin/env sh

curl -o https://www.ostan-collections.net/wiki/index.php/File:Windows1avi.png "OS-Tan Windows 1.0"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Windows2avi.png "OS-Tan Windows 2.0"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Win3-1.jpg "OS-Tan Windows 3.1"
curl -o https://www.ostan-collections.net/wiki/index.php/File:WinNTtan.jpg "OS-Tan Windows NT"
curl -o https://www.ostan-collections.net/wiki/index.php/File:95-tan2.jpg?20120630044724 "OS-Tan Windows 95"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Win97tan.jpg?20110501013251 "OS-Tan Windows 97"
curl -o https://www.ostan-collections.net/wiki/index.php/File:98SEtan.jpg "OS-Tan Windows 98SE"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Win98tan.jpg "OS-Tan Windows 98"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Neptune.gif "OS-Tan Microsoft Neptune"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Odyssey.gif "OS-Tan Microsoft Odysee"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Winme.jpg "OS-Tan Windows Me"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Win2K.jpg "OS-Tan Windows 2000"
curl -o https://in.pinterest.com/pin/900157044269294388 "OS-Tan Windows XP"
curl -o https://neuro.nya.pub/fun/ostan/longhorn.jpg "longhorn-tan.jpg"
curl -o https://www.ostan-collections.net/wiki/index.php/File:Schoolgirlvistan.jpg "vista-tan.jpg" 
curl -o https://www.ostan-collections.net/wiki/index.php/File:WinServer2003tan.jpg "server-2003-tan.jpg" 
curl -o https://www.ostan-collections.net/wiki/index.php/File:Saba-fish.jpg "server-2008-tan.jpg" 
curl -o "https://preview.redd.it/nanami-and-c-sharp-v0-hd3ffl41fc9e1.jpeg?auto=webp&s=2d17d9785329335a3f2d374cef6c17b64fe5eece" "windows7-tan.jpg" 
curl -o https://www.ostan-collections.net/wiki/index.php/File:Yuai.png "windows8-tan.png"
curl -o https://www.ostan-collections.net/wiki/index.php/File:10-full_promo.png "windows10-tan.png"
curl -o https://i.redd.it/c7qkcaernesb1.png "windows11-tan.png"
curl -o "https://preview.redd.it/fanart-ichika-madobe-mascot-windows-11-v0-1n9jlmb54poa1.png?width=1080&crop=smart&auto=webp&s=b99f19f167ff63e549f335541b4638123d10474f" "win11al.webp"